const express=require('express')
const router=express.Router()
const userController=require('../app/controller/userController')
const buildingControler=require('../app/controller/buildingsController')
const roomControler=require('../app/controller/roomController')
const tenantControler=require('../app/controller/tenantController')
const authentication = require('../app/middlewares/authentication')
router.post('/api/building', authentication,   buildingControler.create)
router.post('/api/user/register',userController.create)
router.post('/api/user/login',userController.login)
router.get('/api/user',userController.show)
router.delete('/api/user/:id',authentication,userController.destroy)
router.get('/api/user/register/:id',authentication,userController.showById)
router.get('/api/building',authentication,buildingControler.list)
router.put('/api/building/:id',authentication,buildingControler.update)
router.delete('/api/building/:id',authentication,buildingControler.destroy)
router.post('/api/room',authentication,   roomControler.create)
router.get('/api/room',authentication,roomControler.list)
router.put('/api/room/:id',authentication,roomControler.update)
router.delete('/api/room/:id',authentication,roomControler.destroy)
router.post('/api/tenant',authentication,  tenantControler.create)
router.get('/api/tenant',    authentication,tenantControler.list)
router.put('/api/tenant/:id',    authentication,tenantControler.update)
router.delete('/api/tenant/:id',    authentication,tenantControler.destroy)
router.get('/api/tenant/:id',    authentication,tenantControler.show)
module.exports=router